### ISSUE TITLE
Chromedriver version to use

### ISSUE THREAD

**Issue by shrikrishnaholla** [obivan/autopilot#1]
I tried running this, but got the following error:

```elixir
Generated autopilot app

20:12:14.771 [error] GenServer Autopilot.Simulation terminating         
** (RuntimeError) invalid session id                                    
    (hound 1.1.1) lib/hound/request_utils.ex:52: Hound.RequestUtils.handle_response/3                                                           
    (autopilot 0.1.0) lib/autopilot/simulation.ex:55: Autopilot.Simulation.handle_continue/2                                                    
    (stdlib 3.15) gen_server.erl:695: :gen_server.try_dispatch/4        
    (stdlib 3.15) gen_server.erl:437: :gen_server.loop/7                
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3         
Last message: {:continue, :initialize_simulation}                       

20:12:15.266 [error] GenServer Autopilot.Simulation terminating
** (RuntimeError) invalid session id
    (hound 1.1.1) lib/hound/request_utils.ex:52: Hound.RequestUtils.handle_response/3
    (autopilot 0.1.0) lib/autopilot/simulation.ex:55: Autopilot.Simulation.handle_continue/2
    (stdlib 3.15) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :initialize_simulation}

20:12:15.741 [error] GenServer Autopilot.Simulation terminating
** (RuntimeError) invalid session id
    (hound 1.1.1) lib/hound/request_utils.ex:52: Hound.RequestUtils.handle_response/3
    (autopilot 0.1.0) lib/autopilot/simulation.ex:55: Autopilot.Simulation.handle_continue/2
    (stdlib 3.15) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :initialize_simulation}

20:12:16.201 [error] GenServer Autopilot.Simulation terminating
** (RuntimeError) invalid session id
    (hound 1.1.1) lib/hound/request_utils.ex:52: Hound.RequestUtils.handle_response/3
    (autopilot 0.1.0) lib/autopilot/simulation.ex:55: Autopilot.Simulation.handle_continue/2
    (stdlib 3.15) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :initialize_simulation}
``` 

[This](https://github.com/elixir-wallaby/wallaby/issues/468) makes me opine that this error is probably linked to the difference in the versions of chromedriver I'm using, as compared the the version autopilot has been developed in. Could you share the version of chromedriver you're using?

**Comment by obivan** [comment]
I think this error is most likely due to the difference in versions of Chrome and Chromedriver. I use Chrome version `90.0.4430.212` and Chromedriver version `90.0.4430.24`

**Comment by shrikrishnaholla** [comment]
That helped, thanks :+1:
